version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - "psql_db:/var/lib/postgresql/data"
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - "8080:8080" 
    restart: always
    container_name: brainbox_backend
    volumes:
      - ./backend:/app
    environment:
      - BASE_URL=:8080
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_PORT=5432
      - KEY=SECRETKEYHERE
      - KEY_FOR_ADMIN=SECRETKEYADMINHERE
    depends_on:
      - postgres
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - "4200:4200" 
    container_name: brainbox_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
volumes:
  psql_db:
